# Generated by Django 3.1 on 2022-04-24 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=100, verbose_name='Title')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Price')),
                ('purchaseType', models.CharField(default='Buy', max_length=8, verbose_name='PurchaseType')),
                ('propertyType', models.CharField(default='House', max_length=15, verbose_name='PropertyType')),
                ('bedroom', models.IntegerField(blank=True, default=None, null=True, verbose_name='Bedroom')),
                ('bathroom', models.IntegerField(blank=True, default=None, null=True, verbose_name='Bathroom')),
                ('garage', models.IntegerField(blank=True, default=None, null=True, verbose_name='Garage')),
                ('sqft', models.IntegerField(blank=True, default=None, null=True, verbose_name='Sqft')),
                ('photo_main', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Main Photo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='List Date')),
                ('realtor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtor.realtors')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('scraper_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('scrapertitle', models.CharField(max_length=255, unique=True, verbose_name='ScraperTitle')),
                ('scraper_location', models.CharField(max_length=100, verbose_name='ScraperLocation')),
                ('scraper_price', models.CharField(max_length=100, verbose_name='ScraperPrice')),
                ('scraper_image', models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='ScraperImage')),
            ],
            options={
                'verbose_name': 'Scraper',
                'verbose_name_plural': 'Scrapers',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartment_listing.listings')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
